// import {stringify} from 'circ-json';
// import {Convo, ConvoResponseOption, ConvoStep, FLAG_DELIMITERS} from '../../src/ts/types';

// TODO: figure out how to include these as types without compiling everything
const FLAG_DELIMITERS = ['##', '#', '>', '@', '.', '$'];
type Quote = string | string[];

type ConvoFlagDelimiter = typeof FLAG_DELIMITERS[number];

type ConvoFlagKey<K extends string> =
  | `${K}${ConvoFlagDelimiter}${string}`
  // For a quest phase (somestep$quest:phase2)
  | `${K}$${string}:${string}`
  // For a previous conversation step.
  | `${string}>${K}`;

interface ConvoResponseOption {
  // A conversation flag to determine if this option is available
  condition?: ConvoFlagKey<''>;
  text: string;
  // Optionally trigger some sort of more granular action.
  action?: Action;
  // goto: 'something' continues the convo at the something path
  goto?: string;
  // Include a conversation flag to trigger a goto under different circumstances
  // FIXME: This may or may not work or be useful
  [gotoWithFlag: ConvoFlagKey<'goto'>]: string;
}

interface ConvoStep {
  text?: Quote;
  responses?: ConvoResponseOption[];
  goto?: string;
  queue?: Quote[];
  onQueueFinishGoto?: string;
  action?: Action;
}

interface Convo {
  [stepName: string | ConvoFlagKey<string>]: ConvoStep;
}

const ui = {
  log: (
    message: string,
    options: Omit<NotificationOptions, 'error'> = {timeout: 2000}
  ) => {
    let n: NotificationHandler;
    const prom = new Promise<NotifyDequeueReason>((res) => {
      n = figma.notify(message, {...options, onDequeue: res});
    }) as Promise<NotifyDequeueReason> & {cancel: () => void};
    prom.cancel = () => {
      n.cancel();
    };
    return prom;
  },
  error: (
    message: string,
    options: Omit<NotificationOptions, 'error' | 'onDequeue'> = {timeout: 2000}
  ) => {
    let n: NotificationHandler;
    const prom = new Promise<NotifyDequeueReason>((res) => {
      n = figma.notify(message, {...options, error: true, onDequeue: res});
    }) as Promise<NotifyDequeueReason> & {cancel: () => void};
    prom.cancel = () => {
      n.cancel();
    };
    return prom;
  },
};

const arrowLike = ['ARROW_LINES', 'ARROW_EQUILATERAL'];
function computeDirectionOfEdge(connector: ConnectorNode) {
  if (arrowLike.includes(connector.connectorEndStrokeCap)) {
    if (arrowLike.includes(connector.connectorStartStrokeCap)) {
      return {directional: 'BI'} as const;
    } else {
      return {
        dir: {
          to: 'connectorEnd',
          from: 'connectorStart',
        },
        directional: 'UNI',
      } as const;
    }
  } else {
    if (arrowLike.includes(connector.connectorStartStrokeCap)) {
      return {
        dir: {
          to: 'connectorStart',
          from: 'connectorEnd',
        },
        directional: 'UNI',
      } as const;
    } else {
      return {directional: 'BI'} as const;
    }
  }
}

// get all selected nodes
figma.skipInvisibleInstanceChildren = true;

function getNodeFromId(id: string) {
  return figma.getNodeById(id);
}

// Anything with this shape will be treated as a response option.
// Responses with the same parent will all be grouped together.
const RESPONSE_SHAPE: ShapeWithTextNode['shapeType'] = 'HEXAGON';

// Items with this shape will be treated as conversation steps - anything else is ignored.
const STEP_SHAPE: ShapeWithTextNode['shapeType'] = 'SQUARE';

// These are special responses that get generated by the system so we will ignore them in the figma
const RESPONSE_IGNORE_LIST = ['[ITEM]', '[FRIEND]', '[CRASH]'];

const knownNodes = new Map<string, string>();
const knownEdges: string[] = [];

function cleanTextLine(text?: string): string {
  return (text ?? '')
    .trim()
    .replace(/,$/, '')
    .replace(/^("|“|”|`|'|‘)/, '')
    .replace(/("|“|”|`|'|’)$/, '');
}

function processTextToLines(text?: string): string[] {
  return (
    (text ?? '')
      .split(/\r?\n|\r|\n/g)
      // Remove trailing commas and quotes at the start and end of each line.
      .map((l) => cleanTextLine(l))
      .filter((l) => !!l.trim())
  );
}

function processNodeText(node: ShapeWithTextNode): {
  textLines: string[];
  queue: string[];
} {
  let nodeText = node.text.characters;
  const re = /queue:\n?\[((.*\n|.)*)\]/g;
  const match = re.exec(nodeText);

  let queue: string[] = [];
  if (match?.length) {
    queue = processTextToLines(match[1]);
    nodeText = nodeText.replace(re, '');
  }
  const textLines = processTextToLines(nodeText);
  return {textLines, queue};
}

function getProperStepNameFromNodeName(otherNodeName: string) {
  if (otherNodeName.includes('>')) {
    return otherNodeName.split('>').pop();
  }
  return otherNodeName.split(/[\\#|\\@|\\.|\\$]/)[0];
}

function traverse(node: ShapeWithTextNode, convo: Convo): string {
  if (knownNodes.has(node.id)) {
    return knownNodes.get(node.id)!;
  }
  let stepName = node.id;
  let hasGoto = false;
  if (node.shapeType === STEP_SHAPE) {
    const convoStep: ConvoStep = {};
    const {textLines, queue} = processNodeText(node);

    const firstLine = textLines.shift();

    if (
      !firstLine ||
      firstLine?.startsWith('`') ||
      firstLine?.startsWith(':')
    ) {
      // Generate an automatic step name
      // stepName = `step_${makeshiftConvoStepNameIndex}`;
      // makeshiftConvoStepNameIndex++;
      if (firstLine) {
        textLines.unshift(firstLine);
      }
    } else {
      stepName = firstLine.replace(' ', '');
    }

    const lastLine = textLines.pop();
    if (lastLine?.trim().startsWith('goto')) {
      convoStep.goto = lastLine.replace('goto:', '').trim();
      hasGoto = true;
    } else if (lastLine && lastLine.trim() !== 'end') {
      textLines.push(lastLine);
    }

    // TODO: Handle converting "Play crash!" or "[CRASH]" in a step text to an action.
    // const crashLine = textLines.findIndex(l => l === '[CRASH]' || l.toLowerCase() === 'play crash!');
    // if (crashLine > -1) {
    //   textLines.splice(crashLine, 1);
      
    // }

    if (queue?.length) {
      const queueFinishGotoLine = textLines.findIndex((l) =>
        l.startsWith('onQueueFinishGoto')
      );
      if (queueFinishGotoLine > -1) {
        const onQueueFinishGoto = cleanTextLine(
          textLines[queueFinishGotoLine].replace('onQueueFinishGoto:', '')
        );
        textLines.splice(queueFinishGotoLine, 1);
        convoStep.onQueueFinishGoto = onQueueFinishGoto;
      }
      convoStep.queue = queue;
    }
    if (textLines?.length) {
      convoStep.text = textLines;
    }

    convo[stepName] = convoStep;
  }

  knownNodes.set(node.id, stepName);

  const connectedStepNames: string[] = [];
  const responses: ConvoResponseOption[] = [];
  for (const connector of node.attachedConnectors) {
    if (knownEdges.includes(connector.id)) {
      continue;
    }

    const {directional, dir} = computeDirectionOfEdge(connector);

    if (
      directional === 'BI' ||
      (connector.connectorEnd as ConnectorEndpointEndpointNodeIdAndMagnet)
        ?.endpointNodeId === node.id
    ) {
      // Ignore bidirectional lines and don't go "upstream"
      continue;
    }

    const to = dir.to;

    const otherEndpointNodeId = (
      connector[to] as ConnectorEndpointEndpointNodeIdAndMagnet
    )?.endpointNodeId;

    if (otherEndpointNodeId) {
      const otherNode = getNodeFromId(otherEndpointNodeId);

      if (
        otherNode &&
        otherNode.type === 'SHAPE_WITH_TEXT' &&
        (otherNode.shapeType === STEP_SHAPE ||
          otherNode.shapeType === RESPONSE_SHAPE)
      ) {
        const otherNodeName = traverse(otherNode, convo);
        if (otherNode.shapeType === STEP_SHAPE) {
          connectedStepNames.push(otherNodeName);
        }

        if (otherNode.shapeType === RESPONSE_SHAPE) {
          // This is a response, so it will be linked to the parent node.
          const {textLines} = processNodeText(otherNode);
          // Don't create response options for system responses.
          if (!RESPONSE_IGNORE_LIST.includes(textLines[0])) {
            let condition = undefined;
            if ([...FLAG_DELIMITERS, '!'].includes(textLines[0].charAt(0))) {
              condition = textLines.shift() ?? undefined;
            }
            let goto = undefined;
            if (textLines[textLines.length - 1].startsWith('goto')) {
              goto = textLines.pop()!.replace('goto:', '').trim();
            } else if (otherNodeName) {
              goto = getProperStepNameFromNodeName(otherNodeName);
            }
            // console.log('response goto', goto, otherNodeName, getProperStepNameFromNodeName(otherNodeName), textLines);

            responses.push({
              condition,
              text: textLines.join(' '),
              goto,
            });
          }
        } else if (
          convo[stepName] &&
          !hasGoto &&
          otherNode.shapeType === STEP_SHAPE &&
          otherNodeName &&
          !otherNodeName.startsWith(stepName)
        ) {
          convo[stepName].goto = getProperStepNameFromNodeName(otherNodeName);
        }
      }
    }

    if (responses.length && convo[stepName]) {
      convo[stepName].responses = responses;
    }

    knownEdges.push(connector.id);
  }

  return node.shapeType === RESPONSE_SHAPE
    ? connectedStepNames[0] ?? ''
    : stepName;
}

const selection = figma.currentPage.selection;

if (selection.length !== 1) {
  (async () => {
    await ui.error('Please select a single node as root');
    figma.closePlugin();
  })();
} else {
  const elem = selection[0];
  if (elem.type !== 'SHAPE_WITH_TEXT') {
    (async () => {
      await ui.error(
        'Please select a node (a box with text inside) in your flowchart as root'
      );
      figma.closePlugin();
    })();
  } else {
    const convo: Convo = {};
    traverse(elem, convo);
    // console.log(convo);
    // const stringified = stringify(convo, 2);
    const stringified = JSON.stringify(convo, null, ' ');
    // console.log(stringified);

    (async () => {
      // open window with stringified json inside
      figma.showUI(__html__, {themeColors: true, width: 500, height: 400});
      figma.ui.postMessage(stringified);

      // wait for message from window
      // figma.ui.onmessage = async (msg) => {
      //   if (msg.type === 'copy-success') {
      //     figma.ui.close();
      //     await ui.log('Copied to clipboard');
      //     figma.closePlugin();
      //   } else if (msg.type === 'copy-fail') {
      //     await ui.error('Failed to copy to clipboard');
      //     // we can leave the window open and just do nothing. When the user closes the window, the plugin will close automatically
      //   }
      // };
    })();
  }
}
